-- 백엔드 소유 테이블 중, 관리자 서버가 읽기만 하는 것들.
--
-- 이 서버에는 이 테이블들의 엔티티가 없다. 일부러 만들지 않았다 —
-- 같은 테이블을 매핑한 엔티티가 두 서버에 생기면 컬럼이 바뀔 때 양쪽을 맞춰야 하고,
-- 팀원이 같은 테이블 엔티티를 또 만들면 매핑이 충돌한다.
-- 그래서 필요한 컬럼만 native 쿼리로 읽는다.
--
-- 테스트는 H2 를 ddl-auto=create-drop 으로 쓰는데, 엔티티가 없으면 테이블도 안 생긴다.
-- 그래서 native 쿼리가 참조하는 테이블만 여기서 최소 컬럼으로 만든다.
-- 운영 스키마의 사본이 아니다. 쿼리가 쓰는 컬럼만 있으면 된다.

CREATE TABLE IF NOT EXISTS client_profile (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id   BIGINT       NOT NULL,
    company_name VARCHAR(100) NOT NULL,
    deleted_at   TIMESTAMP
);

CREATE TABLE IF NOT EXISTS project (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS file (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_name VARCHAR(255),
    object_key    VARCHAR(512) NOT NULL
);
