-- 백엔드 소유 테이블 중, 관리자 서버가 읽기만 하는 것들.
--
-- 이 서버에는 이 테이블들의 엔티티가 없다. 일부러 만들지 않았다 —
-- 같은 테이블을 매핑한 엔티티가 두 서버에 생기면 컬럼이 바뀔 때 양쪽을 맞춰야 하고,
-- 팀원이 같은 테이블 엔티티를 또 만들면 매핑이 충돌한다.
-- 그래서 필요한 컬럼만 native 쿼리로 읽는다.
--
-- 테스트는 H2 를 ddl-auto=create-drop 으로 쓰는데, 엔티티가 없으면 테이블도 안 생긴다.
-- 그래서 native 쿼리가 참조하는 테이블만 여기서 최소 컬럼으로 만든다.
-- 운영 스키마의 사본이 아니다. 쿼리가 쓰는 컬럼만 있으면 된다.
--
-- 컬럼을 추가할 때는 반드시 NULL 허용으로 둔다. 이 파일은 여러 테스트가 함께 쓰고,
-- 각 테스트는 자기가 필요한 컬럼만 INSERT 한다. NOT NULL 을 새로 걸면 남의 테스트가 깨진다.

CREATE TABLE IF NOT EXISTS client_profile (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id     BIGINT       NOT NULL,
    company_name   VARCHAR(100) NOT NULL,
    business_no    CHAR(10),
    business_field VARCHAR(40),
    employee_count VARCHAR(30),
    address        VARCHAR(255),
    grade          VARCHAR(20),
    deleted_at     TIMESTAMP
);

CREATE TABLE IF NOT EXISTS freelancer_profile (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id         BIGINT NOT NULL,
    birth_date         DATE,
    address            VARCHAR(255),
    grade              VARCHAR(20),
    ai_matching_agreed BOOLEAN,
    matching_paused    BOOLEAN,
    deleted_at         TIMESTAMP
);

-- 계정당 한 건이다(운영 유니크: uk_condition_freelancer).
--
-- 붙는 키가 account_id 인 것에 주의. 백엔드 SQL 파일에는 freelancer_id 로 적혀 있지만
-- 실제로 값을 쓰는 FreelancerConditionJpaEntity 는 account_id 를 매핑한다.
-- has_freelance_exp / has_freelance_experience 도 같은 식으로 어긋나 있다.
CREATE TABLE IF NOT EXISTS freelancer_condition (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id                BIGINT      NOT NULL,
    job_category              VARCHAR(20),
    job_role                  VARCHAR(40),
    affiliation               VARCHAR(100),
    work_style                VARCHAR(20),
    work_form                 VARCHAR(20),
    pay_unit                  VARCHAR(20),
    pay_amount                NUMERIC(15, 0),
    min_accept_amount         NUMERIC(15, 0),
    available_from            DATE,
    start_negotiable          BOOLEAN,
    period_value              INTEGER,
    period_unit               VARCHAR(10),
    career_years              INTEGER,
    has_freelance_experience  BOOLEAN
);

CREATE TABLE IF NOT EXISTS condition_skill (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    condition_id BIGINT      NOT NULL,
    skill_code   VARCHAR(50) NOT NULL,
    skill_level  VARCHAR(20)
);

-- 한 계정에 공급자가 여러 개일 수 있어 유니크를 걸지 않는다.
-- 조회 쿼리도 그 전제로 connected_at 순서에서 한 건만 고른다.
CREATE TABLE IF NOT EXISTS social_account (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id   BIGINT      NOT NULL,
    provider     VARCHAR(20) NOT NULL,
    connected_at TIMESTAMP
);

-- client_id 는 account.id 가 아니라 client_profile.id 를 가리킨다. (운영 FK: fk_project_client)
CREATE TABLE IF NOT EXISTS project (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id      BIGINT,
    title          VARCHAR(200) NOT NULL,
    status         VARCHAR(30),
    -- 매칭 진단 목록이 착수금 결제 완료 여부로 대상을 고른다.
    payment_status VARCHAR(30),
    deleted_at     TIMESTAMP
);

-- freelancer_id 도 마찬가지로 freelancer_profile.id 다.
CREATE TABLE IF NOT EXISTS contract (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id    BIGINT,
    freelancer_id BIGINT
);

-- payer_account_id 는 account.id 를 직접 가리킨다. 프로필을 거치지 않는 몇 안 되는 테이블이다.
CREATE TABLE IF NOT EXISTS settlement (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payer_account_id BIGINT,
    base_amount      NUMERIC(15, 0),
    status           VARCHAR(30)
);

-- 컬럼 이름은 백엔드 ReviewJpaEntity 기준이다(reviewee_account_id, score).
-- 백엔드의 db/init/02-create-schema.sql 에는 아직 옛 이름(reviewee_id, rating)이 남아 있다.
CREATE TABLE IF NOT EXISTS review (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reviewee_account_id BIGINT,
    score               INTEGER
);

CREATE TABLE IF NOT EXISTS file (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_name VARCHAR(255),
    object_key    VARCHAR(512) NOT NULL
);

-- ---------------------------------------------------------------------------
-- AI 매칭 진단이 읽는 테이블.
--
-- 목록의 issueCount(SQL 식)와 상세의 issues(자바 판정)가 갈리지 않는지 검증하려면
-- 두 경로가 읽는 테이블이 다 있어야 한다. MatchingAdminDiagnosticsTest 참고.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS project_position (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id   BIGINT,
    status       VARCHAR(30),
    job_category VARCHAR(40),
    job_role     VARCHAR(40)
);

CREATE TABLE IF NOT EXISTS position_skill (
    position_id BIGINT,
    skill_code  VARCHAR(40)
);

-- snapshot_type 은 PROJECT / POSITION 두 가지다. 프로젝트 스냅샷은 position_id 가 비어 있다.
CREATE TABLE IF NOT EXISTS matching_snapshot (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id    BIGINT,
    position_id   BIGINT,
    snapshot_type VARCHAR(30)
);

-- 운영은 pgvector 컬럼이 있지만 진단 쿼리는 존재 여부와 model 만 본다.
CREATE TABLE IF NOT EXISTS position_embedding (
    position_id BIGINT,
    model       VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS freelancer_embedding (
    freelancer_id BIGINT,
    model         VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS matching_round (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  BIGINT,
    position_id BIGINT,
    round_no    INTEGER,
    round_type  VARCHAR(30),
    status      VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS matching_candidate (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    round_id    BIGINT,
    position_id BIGINT,
    is_exposed  BOOLEAN
);

CREATE TABLE IF NOT EXISTS matching_request (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  BIGINT,
    position_id BIGINT,
    status      VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS ai_agent_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_type    VARCHAR(30),
    ref_type      VARCHAR(30),
    ref_id        BIGINT,
    model         VARCHAR(50),
    status        VARCHAR(20),
    error_message VARCHAR(255),
    created_at    TIMESTAMP
);
